export {default as Hamburger} from "./Hamburger.svg"
export {default as SearchLogo} from "./SearchLogo.svg"
export {default as DribbleLogo} from "./Dribble.svg"
export {default as HeartIcon } from "./Heart.svg"
export {default as InstaIcon } from "./Instagram.svg"
export {default as XIcon } from "./Twitter.svg"
export {default as PinIcon } from "./Pinterest.svg"
export {default as FbIcon} from "./Facebook.svg"
